name: system_proxy_resolver
repository: https://github.com/ky1vstar/system_proxy_resolver

packages:
  - ./**

scripts:
  get:
    run: melos exec -- flutter pub get

  test:all:
    run: melos run test --no-select

  test:
    run: melos exec --fail-fast -- flutter test
    packageFilters:
      dirExists:
        - test
