name: system_proxy_resolver
description: A new Flutter plugin project.
homepage: https://github.com/ky1vstar/system_proxy_resolver
issue_tracker: https://github.com/ky1vstar/system_proxy_resolver/issues
version: 0.0.1

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  plugin_platform_interface: ^2.0.2
  win32: ^3.1.1

dev_dependencies:
  build_runner: ^2.3.2
  ffigen: ^7.2.1
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  lint: ^1.10.0

flutter:
  plugin:
    platforms:
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
