name: system_proxy_resolver_platform_interface
description: A common platform interface for the system_proxy_resolver plugin.
publish_to: none
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.11.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.0
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  lint: ^2.0.1
  mockito: ^5.0.0
