name: system_proxy_resolver_foundation
description: iOS and macOS implementation of the system_proxy_resolver plugin.
publish_to: none
version: 1.0.1

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: ">=2.11.0"

flutter:
  plugin:
    implements: system_proxy_resolver_federated
    platforms:
      ios:
        ffiPlugin: true
        dartPluginClass: SystemProxyResolverFoundation
      macos:
        ffiPlugin: true
        dartPluginClass: SystemProxyResolverFoundation

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  system_proxy_resolver_platform_interface:
    git:
      url: https://github.com/EmilBaghramyan/system_proxy_resolver.git
      path: system_proxy_resolver_platform_interface

dev_dependencies:
  ffigen: ^7.2.9
  flutter_test:
    sdk: flutter
  lint: ^2.0.1
