name: system_proxy_resolver_federated
description: Federated implementation of the system_proxy_resolver plugin.
publish_to: none
version: 1.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.11.0"

flutter:
  plugin:
    platforms:
      ios:
        default_package: system_proxy_resolver_foundation
      macos:
        default_package: system_proxy_resolver_foundation
      windows:
        default_package: system_proxy_resolver_windows

dependencies:
  flutter:
    sdk: flutter
  system_proxy_resolver_foundation:
    git:
      url: https://github.com/EmilBaghramyan/system_proxy_resolver.git
      path: system_proxy_resolver_foundation
  system_proxy_resolver_platform_interface:
    git:
      url: https://github.com/EmilBaghramyan/system_proxy_resolver.git
      path: system_proxy_resolver_platform_interface
  system_proxy_resolver_windows:
    git:
      url: https://github.com/EmilBaghramyan/system_proxy_resolver.git
      path: system_proxy_resolver_windows

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.1
