name: system_proxy_resolver_example
description: Demonstrates how to use the system_proxy_resolver plugin.
publish_to: 'none'

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  system_proxy_resolver:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  lint: ^1.10.0
  win32_registry: ^1.0.2

dependency_overrides:
  system_proxy_resolver_foundation:
    path: ../../system_proxy_resolver_foundation
  system_proxy_resolver_platform_interface:
    path: ../../system_proxy_resolver_platform_interface

flutter:
  uses-material-design: true
