name: system_proxy_resolver_windows
description: Windows implementation of the system_proxy_resolver plugin.

publish_to: none
version: 1.0.1

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: ">=2.11.0"

flutter:
  plugin:
    implements: system_proxy_resolver_federated
    platforms:
      windows:
        ffiPlugin: true
        dartPluginClass: SystemProxyResolverWindows

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  system_proxy_resolver_platform_interface:
    git:
      url: https://github.com/EmilBaghramyan/system_proxy_resolver.git
      path: system_proxy_resolver_platform_interface
  win32: '5.11.0'

dev_dependencies:
  ffigen: ^7.2.9
  flutter_test:
    sdk: flutter
  lint: ^2.0.1
