name: system_proxy_resolver_windows
description: Windows implementation of the system_proxy_resolver plugin.
homepage: https://github.com/ky1vstar/tree/master/system_proxy_resolver/system_proxy_resolver_windows
issue_tracker: https://github.com/ky1vstar/system_proxy_resolver/issues
version: 0.0.1

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: ">=2.11.0"

flutter:
  plugin:
    implements: system_proxy_resolver
    platforms:
      windows:
        ffiPlugin: true
        dartPluginClass: SystemProxyResolverWindows

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  system_proxy_resolver_platform_interface: ^0.0.1
  win32: '>=2.7.0 <5.0.0'

dev_dependencies:
  ffigen: ^7.2.9
  flutter_test:
    sdk: flutter
  lint: ^2.0.1
