name: system_proxy_resolver
description: A Dart Package to get system proxy settings with support of PAC scripts.

publish_to: none
version: 1.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

platforms:
  ios:
  macos:
  windows:

dependencies:
  system_proxy_resolver_federated: 
    git:
      url: https://github.com/EmilBaghramyan/system_proxy_resolver.git
      path: system_proxy_resolver_federated
  system_proxy_resolver_platform_interface:
    git:
      url: https://github.com/EmilBaghramyan/system_proxy_resolver.git
      path: system_proxy_resolver_platform_interface

dev_dependencies:
  lint: ^2.0.1
  test: ^1.24.1
