name: system_proxy_resolver
description: A Dart Package to get system proxy settings with support of PAC scripts.
homepage: https://github.com/ky1vstar/tree/master/system_proxy_resolver/system_proxy_resolver
issue_tracker: https://github.com/ky1vstar/system_proxy_resolver/issues
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

platforms:
  ios:
  macos:
  windows:

dependencies:
  system_proxy_resolver_federated: ^1.0.0
  system_proxy_resolver_platform_interface: ^1.0.0

dev_dependencies:
  lint: ^2.0.1
  test: ^1.24.1
